I think this will fix it

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -126,11 +126,8 @@ jobs:
 
       - name: Run chaos tests
         run: |
-          echo "NODE_SERVER_DOMAIN is: $NODE_SERVER_DOMAIN"
-          echo "NODE_SERVER_DOMAIN is: ${NODE_SERVER_DOMAIN}"
-          echo "NODE_SERVER_DOMAIN is: ${{ secrets.NODE_SERVER_DOMAIN }}"
-          curl -f "$NODE_SERVER_DOMAIN" + "/chaos-test" || exit 1
-          curl -f "${NODE_SERVER_DOMAIN}/users" -X POST -H "Content-Type: application/json" -d '{"fullname":"test","email":"test@example.com","password":"Test1234"}' || echo "Expected failure under chaos"
+          curl -f "${{ secrets.NODE_SERVER_DOMAIN }}/chaos-test" || exit 1
+          curl -f "${{ secrets.NODE_SERVER_DOMAIN }}/users" -X POST -H "Content-Type: application/json" -d '{"fullname":"test","email":"test@example.com","password":"Test1234"}' || echo "Expected failure under chaos"
     
   deploy:
     runs-on: self-hosted
